### ISSUE TITLE
División de tareas 10-16/06

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#1]
- @elozadaj :
1. Crear bucket de S3  asegurandolo herméticamente
2. Definir estructura de carpetas dentro del bucket 
3. Compartir credenciales con el resto del equipo. 
4. Una vez que Frida comparta csv de datos de movilidad, convertir a parquet para hacer lectura más rápida

- Frida
1. Cargar datos de movilidad a S3
2. Compartir código y resultado de los análisis semanales

- Brenda
1. Examinar el código y los resultados, definir preguntas de investigación interesantes para discusión
2. Crear, una vez que los datos estén cargados, el primer notebook de EDA con preguntas de investigación

**Comment by xuxoramos** [comment]
Frida, esta no es la forma correcta de poner issues en github. Los issues
deben ser atómicos, e individuales. No borres éste, más bien pártelo en
tareas individuales, asígnalos a sus responsables, y márcalos con el label
"task". Ojalá puedas aventarte esto para mañana antes del medio día.

Grax de antemano.

**Comment by xuxoramos** [comment]
Ver #2, #3, #4, #5, #6, #7, #8, #9 para comprobar que este issue se ha partido y asignado individualmente a los responsables.
