### ISSUE TITLE
EDA 1a iteración

### ISSUE THREAD

**Issue by xuxoramos** [sociedat/movicovid#10]
- [x] Establecer baseline
- [x] identificar rutas que existían antes del 23 de Marzo Y QUE CONTINUARON hasta el 1o de Junio, 
- [x] examinar si las georeferencias aportan información para bajar 1 nivel de jerarquía geográfica, 
- [x] comenzar a responder preguntas de investigación (Brenda + Frida)

**Comment by Bcjg23** [comment]
Hice commit a una segunda version en la rama "branch_eda"

https://github.com/sociedat/movicovid/pull/14

**Comment by Bcjg23** [comment]
Hice un commit para el notebook incorporando el segundo item que faltaba y otros análisis

https://github.com/sociedat/movicovid/blob/master/Codigo/EDA_iter1.ipynb

**Comment by xuxoramos** [comment]
Se cierra este issue y se generan otros issues que cubren análisis más extensivos solicitados por @Fridagc.
