### ISSUE TITLE
Crear directorios de bucket

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#11]
Estructurar directorios bucket en S3 para organizar la información almacenada

**Comment by elozadaj** [comment]
Nueva estructura del bucket en S3:

/movicovid
|
|---raw
.......|
.......|---dataforgood
..............|
..............|---\<CSV files>
|---transformed
.......|
.......|---dataforgood
..............|
..............|---\<parquet files>

**Comment by xuxoramos** [comment]
Esto se puede cerrar ya, no, @elozadaj ?

**Comment by elozadaj** [comment]
Nueva estructura del bucket en S3:

/movicovid
|
|---raw
.......|
.......|---dataforgood
..............|
..............|---<CSV files>
|---transformed
.......|
.......|---dataforgood
..............|
..............|---<parquet files>
|---tmp
..............|
..............|---<archivos temporales que aws crea y elimina automáticamente>
|---scripts
..............|
..............|---<scripts que toma aws para correr los pipelines automáticamente>

**Comment by elozadaj** [comment]
Con esta nueva estructura, creo que ya se puede cerrar este issue.

**Comment by xuxoramos** [comment]
Se cierra el issue.
