### ISSUE TITLE
Identificar datasets

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#12]
Buscar e identificar diferentes conjuntos de datos referentes a información sociodemográfica que apoyen en la caracterización de rutas origen-destino

**Comment by xuxoramos** [comment]
Se jala para el siguiente sprint.

**Comment by Bcjg23** [comment]
Datasets externos 

https://github.com/sociedat/movicovid/blob/master/Codigo/Bases_externas.ipynb

**Comment by xuxoramos** [comment]
Se cierra el issue con datasets identificados.
