### ISSUE TITLE
Adquisición de datasets

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#13]
Configurar el pipeline de adquisición del conjuntos de datos para categorizar las rutas origen-destino

**Comment by elozadaj** [comment]
AWS Glue Pipeline:
- [x] Creación de base de datos (para guardar metadata)
- [x] Definición de esquema para archivo CSV dataforgood
- [ ] Definición de esquema para archivo parquet dataforgood
- [ ] Creación de script para transformar de csv a parquet
- [ ] Creación de lambda trigger al agregar CSV en S3

**Comment by elozadaj** [comment]
Al crear los esquemas, se pueden dividir los datos para mejorar la lectura/análisis. Esto podría servir para campos como "fecha", "origen" o "destino".

https://aws.amazon.com/blogs/big-data/work-with-partitioned-data-in-aws-glue/

**Comment by xuxoramos** [comment]
Esto se jala para el siguiente sprint.

**Comment by xuxoramos** [comment]
Esto se cerrará en cuanto @elozadaj levante la infra y ejecución de ETL en cuenta de la sociedat.

**Comment by elozadaj** [comment]
No se utilizará amazon glue por:

- Costo: después de realizar algunas pruebas pequeñas, se comenzó a generar un costo. 
- Overkill: la infraestructura levantada no justifica nuestro objetivo de negocio

Se ha implementado una solución que involucra AWS Lambda y eso es suficiente.

**Comment by elozadaj** [comment]
Se puede cerrar después de corroborar que #6 ya funciona.

**Comment by xuxoramos** [comment]
Se cierra issue.
