### ISSUE TITLE
EDA 2da iteración

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#16]
- [x]  Excluir del análisis las rutas dentro de la misma entidad
- [x]  Identificar rutas que se mantienen y desaparecen
- [x]  Ampliar análisis de rutas y grupos a día de la semana

**Comment by Bcjg23** [comment]
Ya quedo!

https://github.com/sociedat/movicovid/blob/branch_eda/Codigo/EDA_iter2.ipynb

**Comment by xuxoramos** [comment]
Se cierra con PR. Archivo en master: https://github.com/sociedat/movicovid/blob/master/Codigo/EDA_iter2.ipynb
