### ISSUE TITLE
Análisis de georeferencia

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#17]
Validar las georeferencias de las bases de datos de FB para saber si es posible tener polígonos más pequeños que las alcaldías

**Comment by Fridagc** [comment]
Fue posible hacer una correspondencia entre agebs y tiles de FB

![tiles_ages](https://user-images.githubusercontent.com/61208557/87486737-89f4a500-c601-11ea-8748-812098593119.jpg)

**Comment by Fridagc** [comment]
Tiles y AGEBs
[tiles_ageb.zip](https://github.com/sociedat/movicovid/files/4922072/tiles_ageb.zip)

**Comment by xuxoramos** [comment]
@Fridagc agregará a este issue mapa con polígonos de tile + polígonos de AGEB y con eso de puede dar por cerrado.

**Comment by Fridagc** [comment]
[tiles_ageb.zip](https://github.com/sociedat/movicovid/files/4956086/tiles_ageb.zip)


![tiles_ageb_21072020](https://user-images.githubusercontent.com/61208557/88081582-2fe66900-cb46-11ea-9d9d-6eed7017c201.jpg)

**Comment by xuxoramos** [comment]
Se cierra este issue con este análisis geoespacial.
