### ISSUE TITLE
Seleccionar rutas

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#21]
Seleccionar rutas con mayor reducción de frecuencia y con mayor consistencia, de lunes a viernes en horarios hábiles.

**Comment by Bcjg23** [comment]
Análsis de rutas solo en días hábiles.
Rutas finales por confirmar.

https://github.com/sociedat/movicovid/blob/branch_eda/Codigo/EDA_iter3.ipynb

**Comment by Bcjg23** [comment]
Selección de las rutas solo en días hábiles (L-V) y cuya movilidad es menor al 40%

https://github.com/sociedat/movicovid/blob/branch_eda/Codigo/EDA_seleccion_rutas.ipynb

**Comment by xuxoramos** [comment]
Se cierra con PR #31
