### ISSUE TITLE
Integrar R a pipeline

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#28]
Meter una caja de R a pipeline

**Comment by xuxoramos** [comment]
No se integrará el script de R de @Fridagc al pipeline, pero si se integrará el diccionario TILE -> AGEB que genera. @elozadaj creará un 2o diccionario de [num de AGEBs -> TILE] con el que hará JOIN de nuevos registros en los datos semanales y se incorporará esta nueva columna al concentrado de parquet.

**Comment by xuxoramos** [comment]
Se cierra con PR #38.
