### ISSUE TITLE
Guardar csv con unicode correcto

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#29]
Cerciorarse que los csv tengan unicode "UTF-8"

**Comment by elozadaj** [comment]
Frida ha subido un archivo al bucket de movicovid en la siguiente ruta: raw/dataforgood/13072020.csv

Como resultado, se han obtenido 7 carpetas en la ruta: transformed/dataforgood/
Cada carpeta representa los datos de un día de la semana.

**Comment by xuxoramos** [comment]
Se cierra el issue.
