### ISSUE TITLE
Compartir credenciales

### ISSUE THREAD

**Issue by Fridagc** [sociedat/movicovid#4]
Compartir credenciales con el resto del equipo

**Comment by elozadaj** [comment]
Las credenciales fueron compartidas por @xuxoramos e incorporadas a la seguridad del bucket:

@xuxoramos: puede hacer todo
@Fridagc: puede ver/crear/descargar/borrar archivos y carpetas
@Bcjg23 & @elozadaj: pueden ver/descargar archivos
